select * from EDWS_PROD.PROD_EDW_SAS_ADHOC_VIEWS.vw_payment_line; -- to get all payment info, has party account id (SR_ID)

select * from BARCODE_LOOKUP; -- info on barcodes, offers, dates

Select * from EDWS_PROD.PROD_CMT_CAMPAIGN_01.RANKING_FILE_SR_NODUPES -- Ranking file


select * from EDWS_PROD.PROD_EDW_SAS_ADHOC_VIEWS.VW_SHOPPING_TRANSACTION_LINE limit 5;

select DISTINCT
    SHOP.*,
    SKU.SKU,
    SKU.SKU_DESC
FROM EDWS_PROD.PROD_EDW_SAS_ADHOC_VIEWS.VW_SKU_MAP SKU
INNER JOIN EDWS_PROD.PROD_EDW_SAS_ADHOC_VIEWS.VW_EAN EAN
    ON SKU.SKU_KEY = EAN.SKU_KEY
INNER JOIN EDWS_PROD.PROD_EDW_SAS_ADHOC_VIEWS.VW_SHOPPING_TRANSACTION_LINE as SHOP
    ON EAN.EAN_KEY = SHOP.EAN_KEY;
    limit 5;

select * from EDWS_PROD.PROD_EDW_SAS_ADHOC_VIEWS.VW_SKU_MAP limit 5;
select * from EDWS_PROD.PROD_EDW_SAS_ADHOC_VIEWS.VW_EAN;

