USE ROLE RL_PROD_MARKETING_ANALYTICS;
USE DATABASE CUSTOMER_ANALYTICS;
USE WAREHOUSE WHS_PROD_MARKETING_ANALYTICS_LARGE;
USE SCHEMA PRODUCT_REPORTING;


--PPT1
select * from CUSTOMER_ANALYTICS.PRODUCT_REPORTING.PRODUCT_PCA_REPOSITORY;

--PPT2
select * from "CUSTOMER_ANALYTICS"."PRODUCT_REPORTING"."PRODUCT_PPT2_PCA_REPOSITORY";

--PPT3
select * from "CUSTOMER_ANALYTICS"."PRODUCT_REPORTING"."PRODUCT_PPT3_PCA_REPOSITORY";

--PPT4
select * from "CUSTOMER_ANALYTICS"."PRODUCT_REPORTING"."PRODUCT_PPT4_PCA_REPOSITORY";

--Redemptions
select RED_DATE,count(*) from ALL_REDEMPTIONS group by 1 order by 1;

-- Prints
select TRANSACTION_DATE,count(*) from print_master where print_ind = 1 group by 1 order by 1;

--Snapshots -- change campaign name
SELECT * FROM EDWS_PROD.PROD_CMT_CAMPAIGN_01.SNP_X08222CT_POP

-- Price Tendency Model
select * from "CUSTOMER_ANALYTICS"."PRODUCTION"."CVU_PRICE_TENDENCY"
-- shopped in past 6 months - run every period