USE ROLE RL_PROD_MARKETING_ANALYTICS;
USE WAREHOUSE WHS_PROD_MARKETING_ANALYTICS_LARGE;
USE DATABASE CUSTOMER_ANALYTICS;
USE SCHEMA TD_REPORTING;

create or replace temp table sku_list as
SELECT DISTINCT
    SKU.SKU,
    EAN.EAN,
    SKU.SKU_DESC
FROM EDWS_PROD.PROD_EDW_SAS_ADHOC_VIEWS.VW_SKU_MAP SKU
INNER JOIN EDWS_PROD.PROD_EDW_SAS_ADHOC_VIEWS.VW_EAN EAN
   ON SKU.SKU_KEY = EAN.SKU_KEY
WHERE EAN.EAN_END_DATE IS NULL
    AND SKU.SKU in
      (
            )
;

Select * from SKU_list
Order by SKU;
