USE ROLE RL_PROD_MARKETING_ANALYTICS;
USE WAREHOUSE WHS_PROD_MARKETING_ANALYTICS_LARGE;
USE DATABASE CUSTOMER_ANALYTICS;
USE SCHEMA TD_REPORTING;

select * from sku_list order by SKU asc;

select * from EDWS_PROD.PROD_EDW_SAS_ADHOC_VIEWS.VW_SKU_MAP limit 5;
select * from EDWS_PROD.PROD_CMT_PRESENTATION.vw_sku  limit 5;

create or replace temp table sku_list as
SELECT DISTINCT
    SKU.SKU,
    EAN.EAN,
    SKU.SKU_DESC,
    SKU2.CATEGORY_NAME,
    SKU2.SUB_CATEGORY_NAME
FROM EDWS_PROD.PROD_EDW_SAS_ADHOC_VIEWS.VW_SKU_MAP SKU
INNER JOIN EDWS_PROD.PROD_EDW_SAS_ADHOC_VIEWS.VW_EAN EAN
   ON SKU.SKU_KEY = EAN.SKU_KEY
inner join EDWS_PROD.PROD_CMT_PRESENTATION.vw_sku SKU2
on SKU.SKU_KEY = SKU2.SKU_KEY
WHERE EAN.EAN_END_DATE IS NULL
    AND SKU.SKU in (


8037809,

6358505,

8084703,

7444122,

7444144,

7444155,

7815865   );

